a = input("What question number to make script?\n")
print("question"+a+".addEventListener('click', () => {")
print("     if (switcher"+a+" === 0) {")
print("         if (completed"+a+" === 0) {")
print("             switcher"+a+" = 1;")
print("             question"+a+".style.transform = 'scale(1)';")
print("             question"+a+".textContent = '?';")
print("             question"+a+".style.margin = ((window.innerWidth / 100) * 3);")
print("             question"+a+".style.marginLeft = (-window.innerWidth / 50) + 'px';")
print("             question"+a+".style.marginTop = (window.innerWidth / 50) + 'px';")
print("             question"+a+".style.fontSize = originalfontsize;")
print("         } else {")
print("             question"+a+".addEventListener('click', () => {")
print("             question"+a+".style.transform = 'scale(1)';")
print("             question"+a+".textContent = '';")
print("             question"+a+".style.margin = ((window.innerWidth / 100) * 3);")
print("             question"+a+".style.marginLeft = (-window.innerWidth / 50) + 'px';")
print("             question"+a+".style.marginTop = (window.innerWidth / 50) + 'px';")
print("             question"+a+".style.fontSize = originalfontsize;")
print("             question"+a+".style.fontSize = originalfontsize;")
print("             question"+a+".appendChild(cross);")
print("             });")
print("         }")
print("     }")
print("     else {")
print("         question"+a+".style.transform = 'scale(8)';")
print("         question"+a+".textContent = listaquestions[listaplaces["+str(int(a) - 1)+"] - 1];")
print("         question"+a+".style.marginLeft = (((window.innerWidth / 2) - (question1.clientWidth / 2)) - 80) + 'px';")
print("         question"+a+".style.marginTop = (((window.innerHeight / 2) + (question1.clientHeight / 2)) + 100) + 'px';")
print("         question"+a+".style.fontSize = (window.innerWidth / 200) + 'px';")
print("         question"+a+".appendChild(doneInput);")
print("         doneInput.classList.add('butn');")
print("         doneInput.addEventListener('click', () => {")
print("             doneInput.remove();")
print("             question"+a+".textContent = listaanswersya[listaplaces["+str(int(a) - 1)+"] - 1] + '' + listavpointsya[listaplaces["+str(int(a) - 1)+"] - 1] + ' Q Points!';")
print("             completed"+a+" = 1;")
print("             switcher"+a+" = 0;")
print("         });")
print("     }")
print(" });")